# Generated by Django 4.0.1 on 2022-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('codeproduct', models.CharField(max_length=100)),
                ('code', models.ImageField(blank=True, upload_to='code')),
            ],
        ),
    ]
