# Generated by Django 4.0.1 on 2022-01-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='codeproduct',
            new_name='NameProduct',
        ),
        migrations.RenameField(
            model_name='stockproduct',
            old_name='product',
            new_name='productID',
        ),
    ]
