# Generated by Django 4.0.1 on 2022-01-06 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0002_rename_codeproduct_stockproduct_nameproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
