# Generated by Django 4.0.1 on 2022-01-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0003_stockproduct_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createPo', models.CharField(max_length=100)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
