# Generated by Django 4.0.1 on 2022-01-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0004_createpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePo',
        ),
    ]
