# Generated by Django 4.0.1 on 2022-01-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0006_createpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePo',
        ),
    ]
