# Generated by Django 4.0.1 on 2022-01-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0008_createpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpo',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
