# Generated by Django 4.0.1 on 2022-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0010_createpo_nameproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpo',
            old_name='product',
            new_name='productID',
        ),
    ]
