# Generated by Django 4.0.1 on 2022-01-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockproduct', '0011_rename_product_createpo_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
    ]
